[2022-11-30T11:38:43.184+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: pratice_pg.send_email manual__2022-11-30T11:38:36.752309+00:00 [queued]>
[2022-11-30T11:38:43.190+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: pratice_pg.send_email manual__2022-11-30T11:38:36.752309+00:00 [queued]>
[2022-11-30T11:38:43.190+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T11:38:43.190+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-30T11:38:43.190+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T11:38:43.197+0000] {taskinstance.py:1383} INFO - Executing <Task(EmailOperator): send_email> on 2022-11-30 11:38:36.752309+00:00
[2022-11-30T11:38:43.200+0000] {standard_task_runner.py:55} INFO - Started process 1026 to run task
[2022-11-30T11:38:43.203+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pratice_pg', 'send_email', 'manual__2022-11-30T11:38:36.752309+00:00', '--job-id', '758', '--raw', '--subdir', 'DAGS_FOLDER/practice_pg.py', '--cfg-path', '/tmp/tmp2mgacsz3']
[2022-11-30T11:38:43.204+0000] {standard_task_runner.py:83} INFO - Job 758: Subtask send_email
[2022-11-30T11:38:43.241+0000] {task_command.py:376} INFO - Running <TaskInstance: pratice_pg.send_email manual__2022-11-30T11:38:36.752309+00:00 [running]> on host 39d0f50fcfa4
[2022-11-30T11:38:43.286+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pratice_pg
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T11:38:36.752309+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T11:38:36.752309+00:00
[2022-11-30T11:38:43.292+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-11-30T11:38:43.292+0000] {email.py:229} INFO - Email alerting: attempt 1
[2022-11-30T11:38:43.876+0000] {email.py:241} INFO - Sent an alert email to ['admin@comp-gluk.ru']
[2022-11-30T11:38:44.510+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=pratice_pg, task_id=send_email, execution_date=20221130T113836, start_date=20221130T113843, end_date=20221130T113844
[2022-11-30T11:38:44.548+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-30T11:38:44.559+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
