[2022-11-30T11:38:41.291+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: pratice_pg.etl_task manual__2022-11-30T11:38:36.752309+00:00 [queued]>
[2022-11-30T11:38:41.298+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: pratice_pg.etl_task manual__2022-11-30T11:38:36.752309+00:00 [queued]>
[2022-11-30T11:38:41.299+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T11:38:41.299+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-30T11:38:41.299+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T11:38:41.308+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): etl_task> on 2022-11-30 11:38:36.752309+00:00
[2022-11-30T11:38:41.312+0000] {standard_task_runner.py:55} INFO - Started process 1020 to run task
[2022-11-30T11:38:41.314+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pratice_pg', 'etl_task', 'manual__2022-11-30T11:38:36.752309+00:00', '--job-id', '756', '--raw', '--subdir', 'DAGS_FOLDER/practice_pg.py', '--cfg-path', '/tmp/tmp90m77139']
[2022-11-30T11:38:41.317+0000] {standard_task_runner.py:83} INFO - Job 756: Subtask etl_task
[2022-11-30T11:38:41.364+0000] {task_command.py:376} INFO - Running <TaskInstance: pratice_pg.etl_task manual__2022-11-30T11:38:36.752309+00:00 [running]> on host 39d0f50fcfa4
[2022-11-30T11:38:41.405+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pratice_pg
AIRFLOW_CTX_TASK_ID=etl_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T11:38:36.752309+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T11:38:36.752309+00:00
[2022-11-30T11:38:41.410+0000] {base.py:71} INFO - Using connection ID 'pgdb' for task execution.
[2022-11-30T11:38:41.412+0000] {sql.py:315} INFO - Running statement: CREATE TABLE if not exists practice_etl (game_number integer PRIMARY KEY, game_length integer NOT NULL, game_length_ratio numeric NOT NULL);
        TRUNCATE practice_etl;
        INSERT INTO practice_etl SELECT game_number, game_length, game_length/(SELECT MAX(game_length)::numeric from practice) from practice;, parameters: None
[2022-11-30T11:38:41.415+0000] {sql.py:324} INFO - Rows affected: 100
[2022-11-30T11:38:41.415+0000] {postgres.py:96} INFO - NOTICE:  relation "practice_etl" already exists, skipping

[2022-11-30T11:38:41.420+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=pratice_pg, task_id=etl_task, execution_date=20221130T113836, start_date=20221130T113841, end_date=20221130T113841
[2022-11-30T11:38:41.458+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-30T11:38:41.476+0000] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
